/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("RunsObjectPageObjectPage journey");

        opaTest("Navigate to RunsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheRunsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheRunsListGenerated.onTable().iCheckRows();
            When.onTheRunsListGenerated.onTable().iPressRow(0);

            Then.onTheRunsObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            Then.onTheRunsObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.zui_pc_sim.v0001", action: "Simulate", unbound: false } /* , { enabled: true } */);
            // When.onTheRunsObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.zui_pc_sim.v0001", action: "Simulate", unbound: false });
        });


        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheRunsObjectPageGenerated.iCheckNumberOfSections(2);
        });

        opaTest("Check the General section of the Object Page", function (_Given, When, Then) {
            When.onTheRunsObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onTheRunsObjectPageGenerated.iCheckSection({ section: "General" });
            Then.onTheRunsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "CompanyCode" });
            Then.onTheRunsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "FiscalYear" });
            Then.onTheRunsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "FiscalPeriod" });
            Then.onTheRunsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Ledger" });
            Then.onTheRunsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "WBS" });
            Then.onTheRunsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "GLAccount" });
            Then.onTheRunsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Currency" });
            Then.onTheRunsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "TotalAmount" });
            Then.onTheRunsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "CarryType" });
            Then.onTheRunsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ReceiverAccount" });
            Then.onTheRunsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "TransferAccount" });
            Then.onTheRunsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Status" });
            Then.onTheRunsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Message" });
        });

        opaTest("Check the Results section of the Object Page", function (_Given, When, Then) {
            When.onTheRunsObjectPageGenerated.iPressSectionIconTabFilterButton("Results");
            Then.onTheRunsObjectPageGenerated.iCheckSection({ section: "Results" });
            Then.onTheRunsObjectPageGenerated.onTable({ property: "_Simulations" }).iCheckAction({ service: "com.sap.gateway.srvd.zui_pc_sim.v0001", action: "Simulate", unbound: false } /* , { enabled: true } */);
            // When.onTheRunsObjectPageGenerated.onTable({ property: "_Simulations" }).iPressAction({ service: "com.sap.gateway.srvd.zui_pc_sim.v0001", action: "Simulate", unbound: false });
            Then.onTheRunsObjectPageGenerated.onTable({ property: "_Simulations" }).iCheckColumns(undefined, {"CompanyCode":{"header":"CompanyCode"},"FiscalYear":{"header":"FiscalYear"},"FiscalPeriod":{"header":"FiscalPeriod"},"WBS":{"header":"WBS"},"TotalAmount":{"header":"TotalAmount"},"Status":{"header":"Status"},"Message":{"header":"Message"}});
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});