/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("RunsListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheRunsListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheRunsListGenerated.onFilterBar().iCheckFilterField({ property: "CompanyCode" });
            Then.onTheRunsListGenerated.onFilterBar().iCheckFilterField({ property: "FiscalYear" });
            Then.onTheRunsListGenerated.onFilterBar().iCheckFilterField({ property: "FiscalPeriod" });
            Then.onTheRunsListGenerated.onFilterBar().iCheckFilterField({ property: "WBS" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheRunsListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheRunsListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheRunsListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheRunsListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheRunsListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            // When.onTheRunsListGenerated.onTable(defaultTableId).iPressAction("Simulate");
            Then.onTheRunsListGenerated.onTable(defaultTableId).iCheckAction("Simulate", { enabled: false });
            Then.onTheRunsListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"CompanyCode":{"header":"公司代码"},"FiscalYear":{"header":"会计年度"},"FiscalPeriod":{"header":"会计期间"},"WBS":{"header":"WBS"},"GLAccount":{"header":"总账科目"},"TotalAmount":{"header":"本位币金额"},"DebitCreditCode":{"header":"借贷码"},"CarryType":{"header":"结转类型"},"ReceiverAccount":{"header":"结算接收方"},"TransferAccount":{"header":"转出科目"},"Status":{"header":"消息标识"},"Message":{"header":"消息文本"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheRunsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheRunsListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheRunsListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheRunsObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});