/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("SimulationsObjectPageObjectPage journey");

        opaTest("Navigate to SimulationsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheRunsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheRunsListGenerated.onTable().iCheckRows();
            When.onTheRunsListGenerated.onTable().iPressRow(0);

            Then.onTheRunsObjectPageGenerated.iSeeThisPage();
            Then.onTheRunsObjectPageGenerated.onTable({ property: "_Simulations" }).iCheckRows();
            When.onTheRunsObjectPageGenerated.onTable({ property: "_Simulations" }).iPressRow(0);

            Then.onTheSimulationsObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            // Ensure the opened entity is not in Draft state before uncommenting
            // Then.onTheSimulationsObjectPageGenerated.onHeader().iCheckEdit({ visible: true });
            // When.onTheSimulationsObjectPageGenerated.onHeader().iPressEdit();
            Then.onTheSimulationsObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.zui_pc_sim.v0001", action: "Simulate", unbound: false } /* , { enabled: true } */);
            // When.onTheSimulationsObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.zui_pc_sim.v0001", action: "Simulate", unbound: false });
        });


        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheSimulationsObjectPageGenerated.iCheckNumberOfSections(2);
        });

        opaTest("Check the General section of the Object Page", function (_Given, When, Then) {
            When.onTheSimulationsObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onTheSimulationsObjectPageGenerated.iCheckSection({ section: "General" });
            Then.onTheSimulationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "CompanyCode" });
            Then.onTheSimulationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "FiscalYear" });
            Then.onTheSimulationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "FiscalPeriod" });
            Then.onTheSimulationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Ledger" });
            Then.onTheSimulationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "WBS" });
            Then.onTheSimulationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "TotalAmount" });
            Then.onTheSimulationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Status" });
            Then.onTheSimulationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Message" });
            Then.onTheSimulationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "SimulatedAt" });
            Then.onTheSimulationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "SimulatedBy" });
        });

        opaTest("Check the Items section of the Object Page", function (_Given, When, Then) {
            When.onTheSimulationsObjectPageGenerated.iPressSectionIconTabFilterButton("Items");
            Then.onTheSimulationsObjectPageGenerated.iCheckSection({ section: "Items" });
            Then.onTheSimulationsObjectPageGenerated.onTable({ property: "_Items" }).iCheckColumns(undefined, {"ItemNo":{"header":"ItemNo"},"SourceAccount":{"header":"SourceAccount"},"GLAccount":{"header":"GLAccount"},"DebitCredit":{"header":"DebitCredit"},"Amount":{"header":"Amount"},"SourceWBS":{"header":"SourceWBS"},"AccountWBS":{"header":"AccountWBS"},"ManagementWBS":{"header":"ManagementWBS"},"CarryType":{"header":"CarryType"}});
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});